SELECT A.MACHINE_ID,
ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP), 3) AS processing_time
FROM ACTIVITY A, ACTIVITY B
WHERE A.MACHINE_ID = B.MACHINE_ID
AND
A.ACTIVITY_TYPE = 'START'
AND
B.ACTIVITY_TYPE = 'END'
GROUP BY MACHINE_ID;


SELECT
    machine_id,
    ROUND(SUM(CASE WHEN activity_type='start' THEN timestamp*-1 ELSE timestamp END)*1.0
    / (SELECT COUNT(DISTINCT process_id)),3) AS processing_time
FROM
    Activity
GROUP BY machine_id