SELECT A.MACHINE_ID,
       ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP), 3) AS processing_time
FROM ACTIVITY A, ACTIVITY B
WHERE A.MACHINE_ID = B.MACHINE_ID
  AND
    A.ACTIVITY_TYPE = 'START'
  AND
    B.ACTIVITY_TYPE = 'END'
GROUP BY MACHINE_ID;