


SELECT DEPARTMENT.NAME AS DEPARTMENT,
EMPLOYEE.NAME AS EMPLOYEE,
SALARY
FROM
    EMPLOYEE JOIN DEPARTMENT
    ON EMPLOYEE.DEPARTMENTID = DEPARTMENT.ID
WHERE
    (EMPLOYEE.DEPARTMENTID, SALARY) IN
    (SELECT
        DEPARTMENTID, MAX(SALARY)
        FROM
        EMPLOYEE
        GROUP BY DEPARTMENTID
    );